server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangyouzhan/spring-cloud-config.git
      label: master


eureka:
  client:
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为tr
    register-with-eureka: true #表示向注册中心注册自己 默认为trueue,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true
ribbon:
  ReadTimeout: 5000
  ConnecTimeout: 5000


feign:
  hystrix:
    enabled: true



